# Generated by Django 5.0.1 on 2024-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_data', '0002_certificates_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField()),
                ('ism_familiya', models.CharField(max_length=255, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('certificate_link', models.CharField(max_length=255, null=True)),
                ('chek', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
