# Generated by Django 5.0.1 on 2024-01-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_data', '0004_certificate_created_at_certificate_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='updated_at',
        ),
    ]
